# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /home/app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

COPY . .
CMD [ "dotnet", "watch", "run" ]
