version: "2.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres
    volumes:
      - /app/key:/root/.aspnet/DataProtection-Keys
    command:
      [
        "./scripts/wait-for-it.sh",
        "--host=postgres",
        "--port=5432",
        "--",
        "dotnet",
        "ZeroXTeam.dll",
      ]

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /app/_pgData:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
